### ISSUE TITLE
Boundary conditions in 2D Laplace (Lecture 6)

### ISSUE THREAD

**Issue by mustapho** [MATMEK-4270/matmek4270-book#1]
Under the section for boundary conditions in lecture 6 about finding the correct indices of $U$ on the boundaries, it was used a for loop for setting the rows equal to 0, but the elements of the main diagional was adjusted to be $1$. I don't quite get the last part of setting the elements of the diagonal to $1$.

![Uten navn](https://github.com/MATMEK-4270/matmek4270-book/assets/143328060/bdc26593-0733-49cd-97bb-e43433d958a3)

Thanks in advance.

**Comment by mikaem** [comment]
Hi
Every row i in the matrix A represents the equation for the unknown u_i. So by setting all items on the row to zero, except a_{i,i}, which is set to one, you are actually solving

u_i =b_i  (*)

Hence, if you know that node i is on the boundary and the value should be u0, then set the right hand side vector item b_i=u0 and you will solve (*) as

u_i = u0

Hope this helps

**Comment by mustapho** [comment]
That explained it very well. Thank you.
